/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author jjuan
 */
public class CarreraView extends javax.swing.JFrame {

    /**
     * Creates new form CarreraView
     */
    public CarreraView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        lblPikachu = new javax.swing.JLabel();
        lblSonic = new javax.swing.JLabel();
        lblGoku = new javax.swing.JLabel();
        lblNyanCat = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnAccidente = new javax.swing.JButton();
        btnImpulsar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarreraView");

        PanelFondo.setBackground(new java.awt.Color(255, 248, 220));
        PanelFondo.setLayout(null);

        lblPikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Pikachu.gif"))); // NOI18N
        PanelFondo.add(lblPikachu);
        lblPikachu.setBounds(50, 270, 120, 100);

        lblSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Sonic.gif"))); // NOI18N
        PanelFondo.add(lblSonic);
        lblSonic.setBounds(10, 320, 110, 110);

        lblGoku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Goku.gif"))); // NOI18N
        PanelFondo.add(lblGoku);
        lblGoku.setBounds(40, 390, 100, 110);

        lblNyanCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/NyanCat.gif"))); // NOI18N
        PanelFondo.add(lblNyanCat);
        lblNyanCat.setBounds(40, 150, 100, 70);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/ImagenFondo.png"))); // NOI18N
        PanelFondo.add(lblImagen);
        lblImagen.setBounds(0, 0, 850, 520);

        btnIniciar.setBackground(new java.awt.Color(102, 204, 102));
        btnIniciar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 51, 0));
        btnIniciar.setText("Iniciar Carrera");
        btnIniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));
        PanelFondo.add(btnIniciar);
        btnIniciar.setBounds(30, 530, 110, 21);

        btnAccidente.setBackground(new java.awt.Color(255, 221, 51));
        btnAccidente.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnAccidente.setForeground(new java.awt.Color(102, 102, 0));
        btnAccidente.setText("Accidente");
        btnAccidente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 2));
        PanelFondo.add(btnAccidente);
        btnAccidente.setBounds(250, 530, 100, 21);

        btnImpulsar.setBackground(new java.awt.Color(102, 204, 255));
        btnImpulsar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnImpulsar.setForeground(new java.awt.Color(0, 51, 102));
        btnImpulsar.setText("Impulsar");
        btnImpulsar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 2));
        PanelFondo.add(btnImpulsar);
        btnImpulsar.setBounds(510, 530, 100, 21);

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        PanelFondo.add(btnSalir);
        btnSalir.setBounds(740, 530, 75, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarreraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarreraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarreraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarreraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarreraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAccidente;
    private javax.swing.JButton btnImpulsar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblGoku;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNyanCat;
    private javax.swing.JLabel lblPikachu;
    private javax.swing.JLabel lblSonic;
    // End of variables declaration//GEN-END:variables
}
