/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControlVentana;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * Clase que representa la ventana gráfica principal donde se visualiza la carrera.
 * 
 * Contiene los elementos visuales como los botones de acción (iniciar, salir, accidente, impulso),
 * los labels que representan a los competidores, y otros elementos gráficos como los efectos
 * visuales de accidente e impulso.
 * 
 * Esta clase extiende de `JFrame` y es gestionada por el controlador `ControlVentana`.
 * 
 * @author Julian
 */
public class CarreraView extends javax.swing.JFrame {

    /**
     * Referencia al controlador de la ventana.
     * Permite la comunicación entre la vista y la lógica del programa.
     */
    private ControlVentana cVentana;

    /**
     * Constructor de la clase CarreraView.
     * 
     * Recibe el controlador de ventana como parámetro, lo almacena
     * y luego inicializa los componentes gráficos definidos en el formulario.
     * 
     * @param cVentana Referencia al controlador que administra esta vista.
     */
    public CarreraView(ControlVentana cVentana) {
        this.cVentana = cVentana;
        initComponents();
    }

    /**
 * Inicializa todos los componentes gráficos de la ventana CarreraView.
 * 
 * Este método es generado automáticamente por el diseñador de interfaces 
 * de NetBeans y contiene la configuración de todos los elementos de la interfaz:
 * paneles, etiquetas (labels), botones y sus propiedades (posición, tamaño, íconos, colores, etc.).
 * 
 * No se recomienda modificar este código manualmente, ya que puede ser sobrescrito
 * si se vuelve a utilizar el editor gráfico.
 */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        lblAccidente = new javax.swing.JLabel();
        lblImpulso = new javax.swing.JLabel();
        lblPikachu = new javax.swing.JLabel();
        lblGoku = new javax.swing.JLabel();
        lblSonic = new javax.swing.JLabel();
        lblNyanCat = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnAccidente = new javax.swing.JButton();
        btnImpulsar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarreraView");
        setMinimumSize(new java.awt.Dimension(845, 560));

        PanelFondo.setBackground(new java.awt.Color(255, 248, 220));
        PanelFondo.setLayout(null);

        lblAccidente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accidente.gif"))); // NOI18N
        PanelFondo.add(lblAccidente);
        lblAccidente.setBounds(150, 150, 90, 90);

        lblImpulso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fuego.gif"))); // NOI18N
        lblImpulso.setText("jLabel2");
        PanelFondo.add(lblImpulso);
        lblImpulso.setBounds(-70, 260, 120, 90);

        lblPikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Pikachu.gif"))); // NOI18N
        PanelFondo.add(lblPikachu);
        lblPikachu.setBounds(0, 400, 140, 100);

        lblGoku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Goku.gif"))); // NOI18N
        PanelFondo.add(lblGoku);
        lblGoku.setBounds(20, 340, 140, 110);

        lblSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sonic.gif"))); // NOI18N
        PanelFondo.add(lblSonic);
        lblSonic.setBounds(30, 250, 120, 110);

        lblNyanCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nyancatt.gif"))); // NOI18N
        PanelFondo.add(lblNyanCat);
        lblNyanCat.setBounds(20, 150, 140, 92);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImagenFondo.png"))); // NOI18N
        PanelFondo.add(lblImagen);
        lblImagen.setBounds(0, 0, 850, 520);

        btnIniciar.setBackground(new java.awt.Color(102, 204, 102));
        btnIniciar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 51, 0));
        btnIniciar.setText("Iniciar Carrera");
        btnIniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));
        PanelFondo.add(btnIniciar);
        btnIniciar.setBounds(30, 530, 110, 21);

        btnAccidente.setBackground(new java.awt.Color(255, 221, 51));
        btnAccidente.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnAccidente.setForeground(new java.awt.Color(102, 102, 0));
        btnAccidente.setText("Accidente NyanCat");
        btnAccidente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 2));
        PanelFondo.add(btnAccidente);
        btnAccidente.setBounds(250, 530, 130, 21);

        btnImpulsar.setBackground(new java.awt.Color(102, 204, 255));
        btnImpulsar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnImpulsar.setForeground(new java.awt.Color(0, 51, 102));
        btnImpulsar.setText("Impulsar Sonic");
        btnImpulsar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 2));
        PanelFondo.add(btnImpulsar);
        btnImpulsar.setBounds(510, 530, 100, 21);

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        PanelFondo.add(btnSalir);
        btnSalir.setBounds(740, 530, 75, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    /**
 * Devuelve el botón encargado de activar el accidente de NyanCat.
 * @return btnAccidente Botón para aplicar el accidente.
 */
public JButton getBtnAccidente() {
    return btnAccidente;
}

/**
 * Establece el botón que activa el accidente de NyanCat.
 * @param btnAccidente Nuevo botón de accidente.
 */
public void setBtnAccidente(JButton btnAccidente) {
    this.btnAccidente = btnAccidente;
}

/**
 * Devuelve el botón encargado de impulsar a Sonic.
 * @return btnImpulsar Botón para aplicar el impulso.
 */
public JButton getBtnImpulsar() {
    return btnImpulsar;
}

/**
 * Establece el botón que impulsa a Sonic.
 * @param btnImpulsar Nuevo botón de impulso.
 */
public void setBtnImpulsar(JButton btnImpulsar) {
    this.btnImpulsar = btnImpulsar;
}


    /**
 * Devuelve el botón para iniciar la carrera.
 * @return btnIniciar Botón de inicio.
 */
public JButton getBtnIniciar() {
    return btnIniciar;
}

/**
 * Establece el botón para iniciar la carrera.
 * @param btnIniciar Nuevo botón de inicio.
 */
public void setBtnIniciar(JButton btnIniciar) {
    this.btnIniciar = btnIniciar;
}

/**
 * Devuelve el botón para salir de la vista de carrera.
 * @return btnSalir Botón de salir.
 */
public JButton getBtnSalir() {
    return btnSalir;
}

/**
 * Establece el botón para salir de la vista de carrera.
 * @param btnSalir Nuevo botón de salir.
 */
public void setBtnSalir(JButton btnSalir) {
    this.btnSalir = btnSalir;
}


   /**
 * Devuelve la etiqueta (JLabel) correspondiente a Goku.
 * @return lblGoku Etiqueta del competidor Goku.
 */
public JLabel getLblGoku() {
    return lblGoku;
}

/**
 * Establece la etiqueta (JLabel) correspondiente a Goku.
 * @param lblGoku Nueva etiqueta para Goku.
 */
public void setLblGoku(JLabel lblGoku) {
    this.lblGoku = lblGoku;
}

/**
 * Devuelve la etiqueta (JLabel) correspondiente a NyanCat.
 * @return lblNyanCat Etiqueta del competidor NyanCat.
 */
public JLabel getLblNyanCat() {
    return lblNyanCat;
}

/**
 * Establece la etiqueta (JLabel) correspondiente a NyanCat.
 * @param lblNyanCat Nueva etiqueta para NyanCat.
 */
public void setLblNyanCat(JLabel lblNyanCat) {
    this.lblNyanCat = lblNyanCat;
}


    /**
 * Devuelve la etiqueta (JLabel) correspondiente a Pikachu.
 * @return lblPikachu Etiqueta del competidor Pikachu.
 */
public JLabel getLblPikachu() {
    return lblPikachu;
}

/**
 * Establece la etiqueta (JLabel) correspondiente a Pikachu.
 * @param lblPikachu Nueva etiqueta para Pikachu.
 */
public void setLblPikachu(JLabel lblPikachu) {
    this.lblPikachu = lblPikachu;
}

/**
 * Devuelve la etiqueta (JLabel) correspondiente a Sonic.
 * @return lblSonic Etiqueta del competidor Sonic.
 */
public JLabel getLblSonic() {
    return lblSonic;
}

/**
 * Establece la etiqueta (JLabel) correspondiente a Sonic.
 * @param lblSonic Nueva etiqueta para Sonic.
 */
public void setLblSonic(JLabel lblSonic) {
    this.lblSonic = lblSonic;
}


    /**
 * Devuelve la etiqueta (JLabel) que contiene la imagen de fondo de la carrera.
 * @return lblImagen Etiqueta con la imagen de fondo.
 */
public JLabel getLblImagen() {
    return lblImagen;
}

/**
 * Establece la etiqueta (JLabel) que contiene la imagen de fondo de la carrera.
 * @param lblImagen Nueva etiqueta con la imagen de fondo.
 */
public void setLblImagen(JLabel lblImagen) {
    this.lblImagen = lblImagen;
}

/**
 * Devuelve la etiqueta (JLabel) que representa el efecto visual de un accidente en la carrera.
 * @return lblAccidente Etiqueta para mostrar un accidente.
 */
public JLabel getLblAccidente() {
    return lblAccidente;
}

/**
 * Establece la etiqueta (JLabel) que representa el efecto visual de un accidente en la carrera.
 * @param lblAccidente Nueva etiqueta para el accidente.
 */
public void setLblAccidente(JLabel lblAccidente) {
    this.lblAccidente = lblAccidente;
}

/**
 * Devuelve la etiqueta (JLabel) que representa el efecto visual de un impulso en la carrera.
 * @return lblImpulso Etiqueta para mostrar un impulso.
 */
public JLabel getLblImpulso() {
    return lblImpulso;
}

/**
 * Establece la etiqueta (JLabel) que representa el efecto visual de un impulso en la carrera.
 * @param lblImpulso Nueva etiqueta para el impulso.
 */
public void setLblImpulso(JLabel lblImpulso) {
    this.lblImpulso = lblImpulso;
}

    
    
    
// Variables de la interfaz gráfica utilizadas en la vista de la carrera:
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAccidente;
    private javax.swing.JButton btnImpulsar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAccidente;
    private javax.swing.JLabel lblGoku;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImpulso;
    private javax.swing.JLabel lblNyanCat;
    private javax.swing.JLabel lblPikachu;
    private javax.swing.JLabel lblSonic;
    // End of variables declaration//GEN-END:variables
}
