/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControlVentana;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author jjuan
 */
public class CarreraView extends javax.swing.JFrame {
    
    
    private ControlVentana cVentana;
    /**
     * Creates new form CarreraView
     */
    public CarreraView(ControlVentana cVentana) {
        this.cVentana = cVentana;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        lblAccidente = new javax.swing.JLabel();
        lblImpulso = new javax.swing.JLabel();
        lblPikachu = new javax.swing.JLabel();
        lblGoku = new javax.swing.JLabel();
        lblSonic = new javax.swing.JLabel();
        lblNyanCat = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnAccidente = new javax.swing.JButton();
        btnImpulsar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarreraView");
        setMinimumSize(new java.awt.Dimension(845, 560));

        PanelFondo.setBackground(new java.awt.Color(255, 248, 220));
        PanelFondo.setLayout(null);

        lblAccidente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accidente.gif"))); // NOI18N
        PanelFondo.add(lblAccidente);
        lblAccidente.setBounds(150, 150, 90, 90);

        lblImpulso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fuego.gif"))); // NOI18N
        lblImpulso.setText("jLabel2");
        PanelFondo.add(lblImpulso);
        lblImpulso.setBounds(-70, 260, 120, 90);

        lblPikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Pikachu.gif"))); // NOI18N
        PanelFondo.add(lblPikachu);
        lblPikachu.setBounds(0, 400, 140, 100);

        lblGoku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Goku.gif"))); // NOI18N
        PanelFondo.add(lblGoku);
        lblGoku.setBounds(20, 340, 140, 110);

        lblSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sonic.gif"))); // NOI18N
        PanelFondo.add(lblSonic);
        lblSonic.setBounds(30, 250, 120, 110);

        lblNyanCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nyancatt.gif"))); // NOI18N
        PanelFondo.add(lblNyanCat);
        lblNyanCat.setBounds(20, 150, 140, 92);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImagenFondo.png"))); // NOI18N
        PanelFondo.add(lblImagen);
        lblImagen.setBounds(0, 0, 850, 520);

        btnIniciar.setBackground(new java.awt.Color(102, 204, 102));
        btnIniciar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 51, 0));
        btnIniciar.setText("Iniciar Carrera");
        btnIniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));
        PanelFondo.add(btnIniciar);
        btnIniciar.setBounds(30, 530, 110, 21);

        btnAccidente.setBackground(new java.awt.Color(255, 221, 51));
        btnAccidente.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnAccidente.setForeground(new java.awt.Color(102, 102, 0));
        btnAccidente.setText("Accidente NyanCat");
        btnAccidente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 2));
        PanelFondo.add(btnAccidente);
        btnAccidente.setBounds(250, 530, 130, 21);

        btnImpulsar.setBackground(new java.awt.Color(102, 204, 255));
        btnImpulsar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnImpulsar.setForeground(new java.awt.Color(0, 51, 102));
        btnImpulsar.setText("Impulsar Sonic");
        btnImpulsar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 2));
        PanelFondo.add(btnImpulsar);
        btnImpulsar.setBounds(510, 530, 100, 21);

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        PanelFondo.add(btnSalir);
        btnSalir.setBounds(740, 530, 75, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    public JButton getBtnAccidente() {
        return btnAccidente;
    }

    public void setBtnAccidente(JButton btnAccidente) {
        this.btnAccidente = btnAccidente;
    }

    public JButton getBtnImpulsar() {
        return btnImpulsar;
    }

    public void setBtnImpulsar(JButton btnImpulsar) {
        this.btnImpulsar = btnImpulsar;
    }

    public JButton getBtnIniciar() {
        return btnIniciar;
    }

    public void setBtnIniciar(JButton btnIniciar) {
        this.btnIniciar = btnIniciar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLblGoku() {
        return lblGoku;
    }

    public void setLblGoku(JLabel lblGoku) {
        this.lblGoku = lblGoku;
    }

    public JLabel getLblNyanCat() {
        return lblNyanCat;
    }

    public void setLblNyanCat(JLabel lblNyanCat) {
        this.lblNyanCat = lblNyanCat;
    }

    public JLabel getLblPikachu() {
        return lblPikachu;
    }

    public void setLblPikachu(JLabel lblPikachu) {
        this.lblPikachu = lblPikachu;
    }

    public JLabel getLblSonic() {
        return lblSonic;
    }

    public void setLblSonic(JLabel lblSonic) {
        this.lblSonic = lblSonic;
    }

    public JLabel getLblImagen() {
        return lblImagen;
    }

    public void setLblImagen(JLabel lblImagen) {
        this.lblImagen = lblImagen;
    }

    public JLabel getLblAccidente() {
        return lblAccidente;
    }

    public void setLblAccidente(JLabel lblAccidente) {
        this.lblAccidente = lblAccidente;
    }

    public JLabel getLblImpulso() {
        return lblImpulso;
    }

    public void setLblImpulso(JLabel lblImpulso) {
        this.lblImpulso = lblImpulso;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAccidente;
    private javax.swing.JButton btnImpulsar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAccidente;
    private javax.swing.JLabel lblGoku;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImpulso;
    private javax.swing.JLabel lblNyanCat;
    private javax.swing.JLabel lblPikachu;
    private javax.swing.JLabel lblSonic;
    // End of variables declaration//GEN-END:variables
}
