/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControlVentana;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * Clase FinalView
 * 
 * Esta clase representa la ventana final del juego, donde se resumen los resultados
 * obtenidos al finalizar todas las carreras. Muestra visualmente a los competidores
 * y permite cerrar la aplicación.
 * 
 * La vista está asociada al controlador `ControlVentana`, desde donde se gestiona
 * su comportamiento.
 * 
 * Componentes principales (esperados):
 * - Botones para indicar qué personaje ganó más carreras.
 * - Botón para salir del juego.
 * - Etiquetas con imágenes de los competidores.
 * 
 * @author sangr
 */
public class FinalView extends javax.swing.JFrame {
    private ControlVentana cVentana;
    

    /**
     * Creates new form FinalView
     */
    /**
     * Constructor que recibe el controlador de ventanas.
     * Inicializa los componentes gráficos de la vista final.
     *
     * @param cVentana instancia del controlador de la ventana
     */
    public FinalView(ControlVentana cVentana) {
        this.cVentana = cVentana;
        initComponents();
    }

    /**
    * Inicializa todos los componentes gráficos de la interfaz final.
    * Este método es generado automáticamente por el editor de formularios y 
    * configura los botones, etiquetas e imágenes que se muestran en la ventana 
    * de resultados finales.
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFinalPikachu = new javax.swing.JLabel();
        lblGokuFinal = new javax.swing.JLabel();
        lblFinalSonic = new javax.swing.JLabel();
        lblFinalNyan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblVictoriasPika = new javax.swing.JLabel();
        lblVictoriasNyan = new javax.swing.JLabel();
        lblVictoriasGoku = new javax.swing.JLabel();
        lblVictoriasSonic = new javax.swing.JLabel();
        btnGanoPika = new javax.swing.JButton();
        btnGanoNyan = new javax.swing.JButton();
        btnGanoGoku = new javax.swing.JButton();
        btnGanoSonic = new javax.swing.JButton();
        btnSalirFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblFinalPikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Pikachu.gif"))); // NOI18N
        lblFinalPikachu.setText("jLabel1");

        lblGokuFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Goku.gif"))); // NOI18N
        lblGokuFinal.setText("jLabel1");

        lblFinalSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sonic.gif"))); // NOI18N
        lblFinalSonic.setText("jLabel1");

        lblFinalNyan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nyancatt.gif"))); // NOI18N
        lblFinalNyan.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SONIC");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GOKU");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PIKACHU");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NYAN CAT");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VICTORIAS");

        lblVictoriasPika.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasPika.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasPika.setText("0");

        lblVictoriasNyan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasNyan.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasNyan.setText("0");

        lblVictoriasGoku.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasGoku.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasGoku.setText("0");

        lblVictoriasSonic.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasSonic.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasSonic.setText("0");

        btnGanoPika.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoPika.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoPika.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoPika.setText("GANADOR");
        btnGanoPika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoPikaActionPerformed(evt);
            }
        });

        btnGanoNyan.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoNyan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoNyan.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoNyan.setText("GANADOR");
        btnGanoNyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoNyanActionPerformed(evt);
            }
        });

        btnGanoGoku.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoGoku.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoGoku.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoGoku.setText("GANADOR");
        btnGanoGoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoGokuActionPerformed(evt);
            }
        });

        btnGanoSonic.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoSonic.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoSonic.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoSonic.setText("GANADOR");
        btnGanoSonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoSonicActionPerformed(evt);
            }
        });

        btnSalirFinal.setBackground(new java.awt.Color(255, 0, 0));
        btnSalirFinal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSalirFinal.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirFinal.setText("SALIR");
        btnSalirFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGanoPika)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel5)
                                        .addGap(85, 85, 85)
                                        .addComponent(lblVictoriasNyan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(lblFinalNyan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnGanoNyan))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFinalPikachu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblVictoriasPika, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblVictoriasGoku)))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVictoriasSonic)
                                .addGap(33, 33, 33)))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGanoGoku)
                            .addComponent(lblGokuFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFinalSonic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGanoSonic, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirFinal)
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGanoPika, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGanoGoku, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGanoSonic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGanoNyan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFinalPikachu)
                        .addComponent(lblGokuFinal)
                        .addComponent(lblFinalSonic))
                    .addComponent(lblFinalNyan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVictoriasSonic)
                                    .addComponent(lblVictoriasGoku)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(lblVictoriasPika))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblVictoriasNyan)))
                                .addGap(18, 18, 18)
                                .addComponent(btnSalirFinal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
 * Método llamado cuando se presiona el botón "GANADOR" de Pikachu.
 */
    private void btnGanoPikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoPikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoPikaActionPerformed

    /**
 * Método llamado cuando se presiona el botón "GANADOR" de Nyan Cat.
 */
    private void btnGanoNyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoNyanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoNyanActionPerformed

    /**
 * Método llamado cuando se presiona el botón "GANADOR" de Goku.
 */
    private void btnGanoGokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoGokuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoGokuActionPerformed

    /**
 * Método llamado cuando se presiona el botón "GANADOR" de Sonic.
 */
    private void btnGanoSonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoSonicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoSonicActionPerformed

    /**
 * Método llamado cuando se presiona el botón "SALIR".
 * Cierra la ventana de resultados finales.
 */
    private void btnSalirFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirFinalActionPerformed

    

    /**
 * Retorna el botón para salir de la vista final.
 * @return btnSalirFinal botón de salir
 */
public JButton getBtnSalirFinal() {
    return btnSalirFinal;
}

/**
 * Establece el botón para salir de la vista final.
 * @param btnSalirFinal botón de salir
 */
public void setBtnSalirFinal(JButton btnSalirFinal) {
    this.btnSalirFinal = btnSalirFinal;
}

/**
 * Retorna el botón que indica que Goku ganó la carrera.
 * @return btnGanoGoku botón de ganador de Goku
 */
public JButton getBtnGanoGoku() {
    return btnGanoGoku;
}

/**
 * Establece el botón que indica que Goku ganó la carrera.
 * @param btnGanoGoku botón de ganador de Goku
 */
public void setBtnGanoGoku(JButton btnGanoGoku) {
    this.btnGanoGoku = btnGanoGoku;
}


    /**
 * Retorna el botón que indica que Nyan Cat ganó la carrera.
 * @return btnGanoNyan botón de ganador de Nyan Cat
 */
public JButton getBtnGanoNyan() {
    return btnGanoNyan;
}

/**
 * Establece el botón que indica que Nyan Cat ganó la carrera.
 * @param btnGanoNyan botón de ganador de Nyan Cat
 */
public void setBtnGanoNyan(JButton btnGanoNyan) {
    this.btnGanoNyan = btnGanoNyan;
}

/**
 * Retorna el botón que indica que Pikachu ganó la carrera.
 * @return btnGanoPika botón de ganador de Pikachu
 */
public JButton getBtnGanoPika() {
    return btnGanoPika;
}

/**
 * Establece el botón que indica que Pikachu ganó la carrera.
 * @param btnGanoPika botón de ganador de Pikachu
 */
public void setBtnGanoPika(JButton btnGanoPika) {
    this.btnGanoPika = btnGanoPika;
}

    /**
 * Retorna el botón que indica que Sonic ganó la carrera.
 * @return btnGanoSonic botón de ganador de Sonic
 */
public JButton getBtnGanoSonic() {
    return btnGanoSonic;
}

/**
 * Establece el botón que indica que Sonic ganó la carrera.
 * @param btnGanoSonic botón de ganador de Sonic
 */
public void setBtnGanoSonic(JButton btnGanoSonic) {
    this.btnGanoSonic = btnGanoSonic;
}

/**
 * Retorna la etiqueta que muestra la imagen de Nyan Cat en la pantalla final.
 * @return lblFinalNyan etiqueta con la imagen de Nyan Cat
 */
public JLabel getLblFinalNyan() {
    return lblFinalNyan;
}

/**
 * Establece la etiqueta que muestra la imagen de Nyan Cat en la pantalla final.
 * @param lblFinalNyan etiqueta con la imagen de Nyan Cat
 */
public void setLblFinalNyan(JLabel lblFinalNyan) {
    this.lblFinalNyan = lblFinalNyan;
}


    /**
 * Retorna la etiqueta que muestra la imagen de Pikachu en la pantalla final.
 * @return lblFinalPikachu etiqueta con la imagen de Pikachu
 */
public JLabel getLblFinalPikachu() {
    return lblFinalPikachu;
}

/**
 * Establece la etiqueta que muestra la imagen de Pikachu en la pantalla final.
 * @param lblFinalPikachu etiqueta con la imagen de Pikachu
 */
public void setLblFinalPikachu(JLabel lblFinalPikachu) {
    this.lblFinalPikachu = lblFinalPikachu;
}

/**
 * Retorna la etiqueta que muestra la imagen de Sonic en la pantalla final.
 * @return lblFinalSonic etiqueta con la imagen de Sonic
 */
public JLabel getLblFinalSonic() {
    return lblFinalSonic;
}

/**
 * Establece la etiqueta que muestra la imagen de Sonic en la pantalla final.
 * @param lblFinalSonic etiqueta con la imagen de Sonic
 */
public void setLblFinalSonic(JLabel lblFinalSonic) {
    this.lblFinalSonic = lblFinalSonic;
}


    /**
 * Retorna la etiqueta que muestra la imagen de Goku en la pantalla final.
 * @return lblGokuFinal etiqueta con la imagen de Goku
 */
public JLabel getLblGokuFinal() {
    return lblGokuFinal;
}

/**
 * Establece la etiqueta que muestra la imagen de Goku en la pantalla final.
 * @param lblGokuFinal etiqueta con la imagen de Goku
 */
public void setLblGokuFinal(JLabel lblGokuFinal) {
    this.lblGokuFinal = lblGokuFinal;
}

/**
 * Retorna la etiqueta que muestra el número de victorias de Goku.
 * @return lblVictoriasGoku etiqueta con la cantidad de victorias de Goku
 */
public JLabel getLblVictoriasGoku() {
    return lblVictoriasGoku;
}

/**
 * Establece la etiqueta que muestra el número de victorias de Goku.
 * @param lblVictoriasGoku etiqueta con la cantidad de victorias de Goku
 */
public void setLblVictoriasGoku(JLabel lblVictoriasGoku) {
    this.lblVictoriasGoku = lblVictoriasGoku;
}


    /**
 * Retorna la etiqueta que muestra el número de victorias de Nyan Cat.
 * @return lblVictoriasNyan etiqueta con la cantidad de victorias de Nyan Cat
 */
public JLabel getLblVictoriasNyan() {
    return lblVictoriasNyan;
}

/**
 * Establece la etiqueta que muestra el número de victorias de Nyan Cat.
 * @param lblVictoriasNyan etiqueta con la cantidad de victorias de Nyan Cat
 */
public void setLblVictoriasNyan(JLabel lblVictoriasNyan) {
    this.lblVictoriasNyan = lblVictoriasNyan;
}

/**
 * Retorna la etiqueta que muestra el número de victorias de Pikachu.
 * @return lblVictoriasPika etiqueta con la cantidad de victorias de Pikachu
 */
public JLabel getLblVictoriasPika() {
    return lblVictoriasPika;
}

/**
 * Establece la etiqueta que muestra el número de victorias de Pikachu.
 * @param lblVictoriasPika etiqueta con la cantidad de victorias de Pikachu
 */
public void setLblVictoriasPika(JLabel lblVictoriasPika) {
    this.lblVictoriasPika = lblVictoriasPika;
}

/**
 * Retorna la etiqueta que muestra el número de victorias de Sonic.
 * @return lblVictoriasSonic etiqueta con la cantidad de victorias de Sonic
 */
public JLabel getLblVictoriasSonic() {
    return lblVictoriasSonic;
}


    /**
 * Establece la etiqueta que muestra el número de victorias de Sonic.
 * @param lblVictoriasSonic etiqueta con la cantidad de victorias de Sonic
 */
public void setLblVictoriasSonic(JLabel lblVictoriasSonic) {
    this.lblVictoriasSonic = lblVictoriasSonic;
}

   
    /**
 * Declaración de variables de la interfaz FinalView.
 * Incluye botones de acción, etiquetas de texto e imágenes para mostrar 
 * los personajes, sus nombres y la cantidad de victorias obtenidas.
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGanoGoku;
    private javax.swing.JButton btnGanoNyan;
    private javax.swing.JButton btnGanoPika;
    private javax.swing.JButton btnGanoSonic;
    private javax.swing.JButton btnSalirFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFinalNyan;
    private javax.swing.JLabel lblFinalPikachu;
    private javax.swing.JLabel lblFinalSonic;
    private javax.swing.JLabel lblGokuFinal;
    private javax.swing.JLabel lblVictoriasGoku;
    private javax.swing.JLabel lblVictoriasNyan;
    private javax.swing.JLabel lblVictoriasPika;
    private javax.swing.JLabel lblVictoriasSonic;
    // End of variables declaration//GEN-END:variables
}
