/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControlVentana;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author sangr
 */
public class FinalView extends javax.swing.JFrame {
    private ControlVentana cVentana;
    

    /**
     * Creates new form FinalView
     */
    public FinalView(ControlVentana cVentana) {
        this.cVentana = cVentana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFinalPikachu = new javax.swing.JLabel();
        lblGokuFinal = new javax.swing.JLabel();
        lblFinalSonic = new javax.swing.JLabel();
        lblFinalNyan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblVictoriasPika = new javax.swing.JLabel();
        lblVictoriasNyan = new javax.swing.JLabel();
        lblVictoriasGoku = new javax.swing.JLabel();
        lblVictoriasSonic = new javax.swing.JLabel();
        btnGanoPika = new javax.swing.JButton();
        btnGanoNyan = new javax.swing.JButton();
        btnGanoGoku = new javax.swing.JButton();
        btnGanoSonic = new javax.swing.JButton();
        btnSalirFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblFinalPikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Pikachu.gif"))); // NOI18N
        lblFinalPikachu.setText("jLabel1");

        lblGokuFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Goku.gif"))); // NOI18N
        lblGokuFinal.setText("jLabel1");

        lblFinalSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Sonic.gif"))); // NOI18N
        lblFinalSonic.setText("jLabel1");

        lblFinalNyan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/NyanCat.gif"))); // NOI18N
        lblFinalNyan.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SONIC");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GOKU");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PIKACHU");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NYAN CAT");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VICTORIAS");

        lblVictoriasPika.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasPika.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasPika.setText("0");

        lblVictoriasNyan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasNyan.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasNyan.setText("0");

        lblVictoriasGoku.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasGoku.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasGoku.setText("0");

        lblVictoriasSonic.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblVictoriasSonic.setForeground(new java.awt.Color(255, 255, 255));
        lblVictoriasSonic.setText("0");

        btnGanoPika.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoPika.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoPika.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoPika.setText("GANADOR");
        btnGanoPika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoPikaActionPerformed(evt);
            }
        });

        btnGanoNyan.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoNyan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoNyan.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoNyan.setText("GANADOR");
        btnGanoNyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoNyanActionPerformed(evt);
            }
        });

        btnGanoGoku.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoGoku.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoGoku.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoGoku.setText("GANADOR");
        btnGanoGoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoGokuActionPerformed(evt);
            }
        });

        btnGanoSonic.setBackground(new java.awt.Color(0, 204, 0));
        btnGanoSonic.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGanoSonic.setForeground(new java.awt.Color(255, 255, 255));
        btnGanoSonic.setText("GANADOR");
        btnGanoSonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanoSonicActionPerformed(evt);
            }
        });

        btnSalirFinal.setBackground(new java.awt.Color(255, 0, 0));
        btnSalirFinal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSalirFinal.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirFinal.setText("SALIR");
        btnSalirFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lblFinalNyan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVictoriasNyan)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblFinalPikachu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGanoNyan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGanoPika)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVictoriasGoku)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVictoriasSonic, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGanoGoku)
                            .addComponent(lblGokuFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFinalSonic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGanoSonic, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVictoriasPika)
                    .addComponent(btnSalirFinal))
                .addGap(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGanoPika, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGanoGoku, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGanoSonic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGanoNyan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFinalPikachu)
                        .addComponent(lblGokuFinal)
                        .addComponent(lblFinalSonic))
                    .addComponent(lblFinalNyan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVictoriasSonic)
                    .addComponent(lblVictoriasGoku)
                    .addComponent(lblVictoriasPika)
                    .addComponent(lblVictoriasNyan)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addComponent(btnSalirFinal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGanoPikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoPikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoPikaActionPerformed

    private void btnGanoNyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoNyanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoNyanActionPerformed

    private void btnGanoGokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoGokuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoGokuActionPerformed

    private void btnGanoSonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanoSonicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanoSonicActionPerformed

    private void btnSalirFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirFinalActionPerformed

    

    public JButton getBtnSalirFinal() {
        return btnSalirFinal;
    }

    /**
     * @param args the command line arguments
     */
    public void setBtnSalirFinal(JButton btnSalirFinal) {    
        this.btnSalirFinal = btnSalirFinal;
    }

    public JButton getBtnGanoGoku() {
        return btnGanoGoku;
    }

    public void setBtnGanoGoku(JButton btnGanoGoku) {
        this.btnGanoGoku = btnGanoGoku;
    }

    public JButton getBtnGanoNyan() {
        return btnGanoNyan;
    }

    public void setBtnGanoNyan(JButton btnGanoNyan) {
        this.btnGanoNyan = btnGanoNyan;
    }

    public JButton getBtnGanoPika() {
        return btnGanoPika;
    }

    public void setBtnGanoPika(JButton btnGanoPika) {
        this.btnGanoPika = btnGanoPika;
    }

    public JButton getBtnGanoSonic() {
        return btnGanoSonic;
    }

    public void setBtnGanoSonic(JButton btnGanoSonic) {
        this.btnGanoSonic = btnGanoSonic;
    }

    public JLabel getLblFinalNyan() {
        return lblFinalNyan;
    }

    public void setLblFinalNyan(JLabel lblFinalNyan) {
        this.lblFinalNyan = lblFinalNyan;
    }

    public JLabel getLblFinalPikachu() {
        return lblFinalPikachu;
    }

    public void setLblFinalPikachu(JLabel lblFinalPikachu) {
        this.lblFinalPikachu = lblFinalPikachu;
    }

    public JLabel getLblFinalSonic() {
        return lblFinalSonic;
    }

    public void setLblFinalSonic(JLabel lblFinalSonic) {
        this.lblFinalSonic = lblFinalSonic;
    }

    public JLabel getLblGokuFinal() {
        return lblGokuFinal;
    }

    public void setLblGokuFinal(JLabel lblGokuFinal) {
        this.lblGokuFinal = lblGokuFinal;
    }

    public JLabel getLblVictoriasGoku() {
        return lblVictoriasGoku;
    }

    public void setLblVictoriasGoku(JLabel lblVictoriasGoku) {
        this.lblVictoriasGoku = lblVictoriasGoku;
    }

    public JLabel getLblVictoriasNyan() {
        return lblVictoriasNyan;
    }

    public void setLblVictoriasNyan(JLabel lblVictoriasNyan) {
        this.lblVictoriasNyan = lblVictoriasNyan;
    }

    public JLabel getLblVictoriasPika() {
        return lblVictoriasPika;
    }

    public void setLblVictoriasPika(JLabel lblVictoriasPika) {
        this.lblVictoriasPika = lblVictoriasPika;
    }

    public JLabel getLblVictoriasSonic() {
        return lblVictoriasSonic;
    }

    /**
     * @param args the command line arguments
     */
    public void setLblVictoriasSonic(JLabel lblVictoriasSonic) {
        this.lblVictoriasSonic = lblVictoriasSonic;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGanoGoku;
    private javax.swing.JButton btnGanoNyan;
    private javax.swing.JButton btnGanoPika;
    private javax.swing.JButton btnGanoSonic;
    private javax.swing.JButton btnSalirFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFinalNyan;
    private javax.swing.JLabel lblFinalPikachu;
    private javax.swing.JLabel lblFinalSonic;
    private javax.swing.JLabel lblGokuFinal;
    private javax.swing.JLabel lblVictoriasGoku;
    private javax.swing.JLabel lblVictoriasNyan;
    private javax.swing.JLabel lblVictoriasPika;
    private javax.swing.JLabel lblVictoriasSonic;
    // End of variables declaration//GEN-END:variables
}
