/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControlVentana;
import javax.swing.JButton;

/**
 *
 * @author hailen
 */
public class InicioView extends javax.swing.JFrame {

    private ControlVentana cVentana;

    /**
     * Creates new form InicioView
     */
    public InicioView(ControlVentana cVentana) {
        
        this.cVentana = cVentana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 500));

        PanelFondo.setBackground(new java.awt.Color(255, 248, 220));
        PanelFondo.setLayout(null);

        btnJugar.setBackground(new java.awt.Color(0, 0, 0));
        btnJugar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        PanelFondo.add(btnJugar);
        btnJugar.setBounds(200, 390, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/AMAZONRACE.png"))); // NOI18N
        PanelFondo.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnJugar() {
        return btnJugar;
    }

    public void setBtnJugar(JButton btnJugar) {
        this.btnJugar = btnJugar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
