/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControlVentana;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 * Vista principal del juego, que permite al usuario iniciar la partida.
 * Muestra botones para seleccionar archivos, iniciar el juego y ver créditos.
 * También permite seleccionar una ruta para guardar resultados.
 * 
 * Controlada por la clase ControlVentana.
 * 
 * @author hailen
 */
public class InicioView extends javax.swing.JFrame {

    private ControlVentana cVentana;

    /**
     * Constructor de la clase InicioView.
     * Inicializa los componentes de la interfaz y recibe el controlador asociado.
     *
     * @param cVentana instancia del controlador que gestiona esta vista.
     */
    public InicioView(ControlVentana cVentana) {

        this.cVentana = cVentana;
        initComponents();
    }

    /**
     * Método que inicializa y configura todos los componentes gráficos de la ventana de inicio.
     * Se define la apariencia del panel de fondo, el botón "JUGAR" y la imagen principal.
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        lblImagenInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 500));

        PanelFondo.setBackground(new java.awt.Color(255, 248, 220));
        PanelFondo.setLayout(null);

        btnJugar.setBackground(new java.awt.Color(0, 0, 0));
        btnJugar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        PanelFondo.add(btnJugar);
        btnJugar.setBounds(200, 390, 120, 40);

        lblImagenInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AMAZONRACE.png"))); // NOI18N
        PanelFondo.add(lblImagenInicio);
        lblImagenInicio.setBounds(0, 0, 500, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
 * Acción que se ejecuta al presionar el botón "JUGAR".
 * Generalmente se utiliza para iniciar el juego o cambiar de ventana.
 * @param evt Evento de acción generado por el botón.
 */
    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
 * Obtiene el botón que permite iniciar el juego.
 * 
 * @return btnJugar El botón "JUGAR".
 */
public JButton getBtnJugar() {
    return btnJugar;
}

/**
 * Establece el botón que permite iniciar el juego.
 * 
 * @param btnJugar El nuevo botón "JUGAR".
 */
public void setBtnJugar(JButton btnJugar) {
    this.btnJugar = btnJugar;
}

/**
 * Obtiene la etiqueta que contiene la imagen de inicio.
 * 
 * @return lblImagenInicio La etiqueta con la imagen de inicio.
 */
public JLabel getLblImagenInicio() {
    return lblImagenInicio;
}

/**
 * Establece la etiqueta que contiene la imagen de inicio.
 * 
 * @param lblImagenInicio La nueva etiqueta con la imagen de inicio.
 */
public void setLblImagenInicio(JLabel lblImagenInicio) {
    this.lblImagenInicio = lblImagenInicio;
}

    
    

    /**
 * Abre un cuadro de diálogo para que el usuario seleccione un archivo de imágenes.
 *
 * @return El archivo seleccionado por el usuario o {@code null} si no se seleccionó ninguno.
 */
    public File rutaJfileChooserImagenes() {
        File f;
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        fc.showDialog(null, "Seleccionar Archivo de IMAGENES");

        f = fc.getSelectedFile();
        return f;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel lblImagenInicio;
    // End of variables declaration//GEN-END:variables
}
